
# Usa a imagem do Node.js com Angular CLI pré-instalado
FROM node:22.12.0
# Instala o Angular CLI globalmente
RUN npm install -g @angular/cli
# Define o diretório de trabalho dentro do container
WORKDIR /app
# Copia os arquivos de dependências
COPY package*.json ./
# Instala as dependências do projeto
RUN npm install
# Copia o restante do projeto para o container
COPY . .
# Expõe a porta padrão do Angular (4200)
EXPOSE 4200
# Comando para rodar o Angular em modo desenvolvimento com mapeamento de host
CMD ["ng", "serve", "--host", "0.0.0.0"]


# cria a pasta app.
# copia os arquivos.
# instala o npm e depois o angular.
# exponhe uma porta.
# executa o comando ngServe para executar o angular.
# o 0.0.0.0 é para evitar o localhost e para mapear as portas.

#build da imagem: docker build -t angular-docker .
#criando container: docker run -p 4200:4200 angular-docker

#docker build -t angular-dev .
#docker run -d -p 4200:4200 -v ${PWD}:/app -v /app/node_modules angular-dev

#com docker-compose: docker-compose up angular-app

#comando que roda a imagem: docker-compose up pet.api pet.frontend.dev


