version: '3.4'

services:
  pet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=DbPet;User Id=docker_user;Password=123456;MultipleActiveResultSets=true;TrustServerCertificate=True
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  pet.frontend.dev:
    environment:
      - NODE_ENV=development
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true