version: '3.4'

services:
  pet.api:
    image: ${DOCKER_REGISTRY-}petapi
    build:
      context: .
      dockerfile: src/Pet.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - pet-network

  pet.frontend.dev:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.dev
    networks:
      - pet-network

  pet.frontend.prod:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge